### ISSUE TITLE
Unable to install fbprophet using pip on watson studio cloud

### ISSUE THREAD

**Issue by charles2588** [IBM/watson-stock-market-predictor#17]
!pip install --user fbprophet

ERROR: Complete output from command /opt/conda/envs/Python36/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/home/dsxuser/.tmp/pip-install-66hlx4dn/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /home/dsxuser/.tmp/pip-wheel-divwrn93 --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet

Alternative is to use

!conda install -c conda-forge fbprophet -y

**Comment by oalansilva** [comment]
Good Morning

I already did two forms without my case is giving the error below:
ModuleNotFoundError: No module named 'fbprophet'
Can you help me?
